In [70]:
import os
import subprocess

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.svm import NuSVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import cross_val_score
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [45]:
#citesc setul de date
datasets = pd.read_csv('ObesityDataSet.csv')

In [46]:
#afisez primele 5 
datasets.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2,3,Sometimes,no,2.0,no,0.0,1,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3,3,Sometimes,yes,3.0,yes,3.0,0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2,3,Sometimes,no,2.0,no,2.0,1,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3,3,Sometimes,no,2.0,no,2.0,0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2,1,Sometimes,no,2.0,no,0.0,0,Sometimes,Public_Transportation,Overweight_Level_I

In [47]:
datasets.shape

(499, 17)

In [48]:
datasets.dtypes

Gender                             object
Age                               float64
Height                            float64
Weight                            float64
family_history_with_overweight     object
FAVC                               object
FCVC                                int64
NCP                                 int64
CAEC                               object
SMOKE                              object
CH2O                              float64
SCC                                object
FAF                               float64
TUE                                 int64
CALC                               object
MTRANS                             object
NObeyesdad                         object
dtype: object

In [49]:
le_ObesityLevel = LabelEncoder()
le_ObesityLevel.fit(datasets['NObeyesdad']) 
data_encoded_ObL = le_ObesityLevel.transform(datasets['NObeyesdad'])
data_encoded_ObL

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

In [50]:
le_ObesityLevel.classes_

array(['Normal_Weight', 'Overweight_Level_I'], dtype=object)

In [51]:
datasets_1 = datasets.apply(le_ObesityLevel.fit_transform) # for all the attributes
datasets_1

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3,0
1,0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3,0
2,1,9,33,46,1,0,1,1,2,0,2,0,3,1,1,3,0
3,1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4,1
4,1,8,31,60,0,0,1,0,2,0,2,0,0,0,2,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,0,4,19,32,0,1,2,1,2,0,2,0,0,0,2,3,0
495,1,5,33,25,1,1,2,0,0,0,0,1,0,0,3,2,0
496,1,4,25,13,1,1,1,1,2,0,2,0,0,2,2,3,0
497,1,6,8,5,0,0,1,1,2,0,2,0,2,1,2,3,0
498,0,12,21,76,1,1,2,1,2,0,1,0,1,1,2,3,1

In [52]:
X = datasets_1[datasets.columns.drop('NObeyesdad')]
Y = datasets_1['NObeyesdad']

In [53]:
X

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3
1,0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3
2,1,9,33,46,1,0,1,1,2,0,2,0,3,1,1,3
3,1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4
4,1,8,31,60,0,0,1,0,2,0,2,0,0,0,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,0,4,19,32,0,1,2,1,2,0,2,0,0,0,2,3
495,1,5,33,25,1,1,2,0,0,0,0,1,0,0,3,2
496,1,4,25,13,1,1,1,1,2,0,2,0,0,2,2,3
497,1,6,8,5,0,0,1,1,2,0,2,0,2,1,2,3
498,0,12,21,76,1,1,2,1,2,0,1,0,1,1,2,3

In [54]:
Y

0      0
1      0
2      0
3      1
4      1
      ..
494    0
495    0
496    0
497    0
498    1
Name: NObeyesdad, Length: 499, dtype: int64

In [55]:
#Impart dataset-ul in Training set si Test set
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.25)

In [56]:
X_Train

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
12,1,8,17,19,0,0,2,1,2,0,3,0,3,0,2,3
329,0,5,17,51,1,1,2,1,2,0,0,0,0,1,2,3
146,0,10,8,10,0,0,2,1,1,0,2,0,3,2,1,3
312,0,2,12,20,0,1,2,1,2,0,0,0,4,0,3,3
286,0,7,12,26,0,1,1,1,2,0,0,0,2,1,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,1,4,25,17,0,1,1,2,2,0,2,0,3,1,2,3
172,0,9,17,23,0,0,2,0,2,0,2,0,2,2,2,3
452,1,9,28,37,0,0,2,1,3,0,2,0,3,1,2,0
140,1,9,42,31,1,1,2,1,1,0,3,0,2,1,2,3
402,1,14,36,71,1,1,2,0,1,0,2,0,3,1,2,4

In [57]:
print(len(X_Train))
print(len(X_Test))
print(len(Y_Train))
print(len(Y_Test))

374
125
374
125

In [58]:
#Feature Scaling
stdScaler = StandardScaler() #Standardize features by removing the mean and scaling to unit variance
X_Train = stdScaler.fit_transform(X_Train)
X_Test = stdScaler.transform(X_Test)

In [59]:
X_Train

array([[ 0.8837151 , -0.19193735, -0.42275006, ..., -0.88585545,
        -0.39456281,  0.42720711],
       [-1.13158641, -0.64246812, -0.42275006, ...,  0.46093292,
        -0.39456281,  0.42720711],
       [-1.13158641,  0.10841649, -1.30823651, ...,  1.80772128,
        -1.99854641,  0.42720711],
       ...,
       [ 0.8837151 , -0.04176043,  0.65951114, ...,  0.46093292,
        -0.39456281, -1.85529947],
       [ 0.8837151 , -0.04176043,  2.0369345 , ...,  0.46093292,
        -0.39456281,  0.42720711],
       [ 0.8837151 ,  0.70912418,  1.4466102 , ...,  0.46093292,
        -0.39456281,  1.18804264]])

In [60]:
Y_Train

12     0
329    1
146    0
312    0
286    0
      ..
301    0
172    0
452    0
140    0
402    1
Name: NObeyesdad, Length: 374, dtype: int64

In [61]:
#SVC

In [62]:
#Antrenarea clasificatorului in Training set
svc = SVC(kernel = 'linear', probability =True, random_state = 0)
svc.fit(X_Train, Y_Train)

SVC(kernel='linear', probability=True, random_state=0)

In [63]:
#Prezicerea rezultatelor setului de testare
Y_Pred = svc.predict(X_Test)
Y_Pred

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [64]:
Y_Test

84     1
307    0
322    0
420    0
335    0
      ..
97     0
114    0
261    1
392    0
316    0
Name: NObeyesdad, Length: 125, dtype: int64

In [65]:
my_test0 = [0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3]
svc.predict([my_test0])

array([1])

In [66]:
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
print("Confusion matrix:")
matrix = confusion_matrix(Y_Test, Y_Pred)
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_Test, Y_Pred))
print("Precision score:",metrics.precision_score(Y_Test, Y_Pred))
print("Recall score:",metrics.recall_score(Y_Test, Y_Pred))
print("F1 score:",f1_score(Y_Test, Y_Pred))

Confusion matrix:
[[76  1]
 [ 8 40]]
Accuracy score: 0.928
Precision score: 0.975609756097561
Recall score: 0.8333333333333334
F1 score: 0.8988764044943819

In [67]:
#BAGGING: Random Forest Clasifier
num_trees = 100
max_features = 2
rmodel = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
results2 = cross_val_score(rmodel, X, Y, cv=5)
print(results2.mean())

#1. split the dataset: train and test and then fit the classifier using X_train and Y_train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)
rmodel.fit(X_train,Y_train)

#2. test the classifier using 3 samples
my_tests = [[0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3],[0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3],[1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4]]
Y_prediction_test= rmodel.predict(my_tests)
print(Y_prediction_test)

#3. print the predictions 
Y_prediction = rmodel.predict(X_test)
print("Y_prediction:",Y_prediction)
print("Y_test:",Y_test)

#4. check/test 5 metrics for classification
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_test, Y_prediction)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_test, Y_prediction))
print("Precision score:",metrics.precision_score(Y_test, Y_prediction))
print("Recall score:",metrics.recall_score(Y_test, Y_prediction))
print("F1 score:",f1_score(Y_test, Y_prediction))

0.8797171717171718
[0 0 1]
Y_prediction: [1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 0 0 1
 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0]
Y_test: 90     1
254    0
283    0
444    0
474    0
      ..
381    0
56     0
439    0
60     0
208    0
Name: NObeyesdad, Length: 100, dtype: int64
Confusion Matrix:
[[57  3]
 [ 9 31]]
Accuracy score: 0.88
Precision score: 0.9117647058823529
Recall score: 0.775
F1 score: 0.8378378378378379

/home/izabella/anaconda3/envs/my_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [69]:
#BAGGING: EXTRATREES
clf = ExtraTreesClassifier(n_estimators=10, max_depth=None, min_samples_split=2, random_state=0)
scores = cross_val_score(clf, X, Y, cv=5)
print(scores.mean())

#1. split the dataset: train and test and then fit the classifier using X_train and Y_train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)
rmodel.fit(X_train,Y_train)

#2. test the classifier using 3 samples
my_tests = [[0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3],[0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3],[1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4]]
Y_prediction_test= rmodel.predict(my_tests)
print(Y_prediction_test)

#3. print the predictions
Y_prediction = rmodel.predict(X_test)
print("Y_prediction:",Y_prediction)
print("Y_test:",Y_test)

#4. check/test 5 metrics for classification
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_test, Y_prediction)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_test, Y_prediction))
print("Precision score:",metrics.precision_score(Y_test, Y_prediction))
print("Recall score:",metrics.recall_score(Y_test, Y_prediction))
print("F1 score:",f1_score(Y_test, Y_prediction))

0.8176161616161617
[0 0 1]
Y_prediction: [1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 0 0 1
 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0]
Y_test: 90     1
254    0
283    0
444    0
474    0
      ..
381    0
56     0
439    0
60     0
208    0
Name: NObeyesdad, Length: 100, dtype: int64
Confusion Matrix:
[[56  4]
 [ 7 33]]
Accuracy score: 0.89
Precision score: 0.8918918918918919
Recall score: 0.825
F1 score: 0.8571428571428571

/home/izabella/anaconda3/envs/my_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [75]:
#BOOSTING: ADABOOST
seed = 5
num_trees = 30
kfold = model_selection.KFold(n_splits=10, shuffle=True, random_state=seed)

model = AdaBoostClassifier(base_estimator = svc, n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)

print(results)
print(results.mean())

#split the dataset: train + test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)
model.fit(X_train,Y_train)

#Predict the response for test dataset
Y_prediction = model.predict(X_test)
print("Y_prediction:",Y_prediction)
print("Y_test:",Y_test)

#test the model using 3 samples
my_tests = [[0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3],[0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3],[1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4]]
Y_prediction_test= model.predict(my_tests)
print("Prediction form my given test:",Y_prediction_test)

#check/test 5 metrics for classification
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_test, Y_prediction)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_test, Y_prediction))
print("Precision score:",metrics.precision_score(Y_test, Y_prediction))
print("Recall score:",metrics.recall_score(Y_test, Y_prediction))
print("F1 score:",f1_score(Y_test, Y_prediction))

[0.92       0.98       0.88       0.9        0.94       0.96
 0.9        0.94       0.82       0.81632653]
0.9056326530612246
Y_prediction: [1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0
 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0]
Y_test: 90     1
254    0
283    0
444    0
474    0
      ..
381    0
56     0
439    0
60     0
208    0
Name: NObeyesdad, Length: 100, dtype: int64
Prediction form my given test: [0 0 1]
Confusion Matrix:
[[60  0]
 [ 6 34]]
Accuracy score: 0.94
Precision score: 1.0
Recall score: 0.85
F1 score: 0.9189189189189189

/home/izabella/anaconda3/envs/my_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

In [76]:
#GRADIENT BOOSTING
num_trees = 100
kfold = model_selection.KFold(n_splits=10)

model = GradientBoostingClassifier(n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

X_for_train, X_for_test, Y_for_train, Y_for_test = train_test_split(X, Y, test_size = 0.15, random_state = 0)

my_test = [[0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3],[0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3],[1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4]]

# Train GradientBoostingClassifier: fitting the X and Y
gboost = GradientBoostingClassifier(n_estimators=100,learning_rate=1)
gboost.fit(X_for_train, Y_for_train)

#Predict the response for test dataset
Y_prediction = gboost.predict(X_test)
# test using the sample given: test the model using 3 new samples, and print the results
Y_prediction_test= gboost.predict(my_test)

#print the predictions
print("Prediction form my given test:",Y_prediction_test)
print("Prediction:",Y_prediction)

#check/test 5 metrics for classification
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_test, Y_prediction)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_test, Y_prediction))
print("Precision score:",metrics.precision_score(Y_test, Y_prediction))
print("Recall score:",metrics.recall_score(Y_test, Y_prediction))
print("F1 score:",f1_score(Y_test, Y_prediction))

0.9638775510204081
Prediction form my given test: [0 0 1]
Prediction: [1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0
 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0]
Confusion Matrix:
[[60  0]
 [ 3 37]]
Accuracy score: 0.97
Precision score: 1.0
Recall score: 0.925
F1 score: 0.961038961038961

/home/izabella/anaconda3/envs/my_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(

In [170]:
#NuSVC

In [79]:
nusvc = NuSVC (nu =0.5 , kernel ='rbf', degree =3, gamma ='auto', coef0 =0.0, shrinking =True, probability =True, 
               tol =0.001, cache_size =200, class_weight = None, verbose =False, max_iter = -1, random_state = None)
nusvc.fit(X_Train, Y_Train)

NuSVC(gamma='auto', probability=True)

In [80]:
#Prezicerea rezultatelor setului de testare
Y_Pred_nusvc = nusvc.predict(X_Test)
Y_Pred_nusvc

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
Y_Test

84     1
307    0
322    0
420    0
335    0
      ..
97     0
114    0
261    1
392    0
316    0
Name: NObeyesdad, Length: 125, dtype: int64

In [82]:
my_test1 = [0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3]
nusvc.predict([my_test1])

array([1])

In [83]:
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
print("Confusion matrix:")
matrix = confusion_matrix(Y_Test, Y_Pred)
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_Test, Y_Pred))
print("Precision score:",metrics.precision_score(Y_Test, Y_Pred))
print("Recall score:",metrics.recall_score(Y_Test, Y_Pred))
print("F1 score:",f1_score(Y_Test, Y_Pred))

Confusion matrix:
[[76  1]
 [ 8 40]]
Accuracy score: 0.928
Precision score: 0.975609756097561
Recall score: 0.8333333333333334
F1 score: 0.8988764044943819

In [84]:
#Random Forest Clasifier
num_trees = 100
max_features = 5
rmodel = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
results2 = cross_val_score(rmodel, X, Y, cv=5)
print(results2.mean())

#1. split the dataset: train and test and then fit the classifier using X_train and Y_train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)
rmodel.fit(X_train,Y_train)

#2. test the classifier using 3 samples
my_tests = [[0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3],[0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3],[1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4]]
Y_prediction_test= rmodel.predict(my_tests)
print(Y_prediction_test)

#3. print the predictions 
Y_prediction = rmodel.predict(X_test)
print("Y_prediction:",Y_prediction)
print("Y_test:",Y_test)

#4. check/test 5 metrics for classification
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_test, Y_prediction)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_test, Y_prediction))
print("Precision score:",metrics.precision_score(Y_test, Y_prediction))
print("Recall score:",metrics.recall_score(Y_test, Y_prediction))
print("F1 score:",f1_score(Y_test, Y_prediction))

0.9017373737373736
[0 0 1]
Y_prediction: [1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 0 0 0
 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0]
Y_test: 90     1
254    0
283    0
444    0
474    0
      ..
381    0
56     0
439    0
60     0
208    0
Name: NObeyesdad, Length: 100, dtype: int64
Confusion Matrix:
[[57  3]
 [ 7 33]]
Accuracy score: 0.9
Precision score: 0.9166666666666666
Recall score: 0.825
F1 score: 0.8684210526315789

/home/izabella/anaconda3/envs/my_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [85]:
#EXTRA TREE
clf = ExtraTreesClassifier(n_estimators=10, max_depth=None, min_samples_split=2, random_state=0)
scores = cross_val_score(clf, X, Y, cv=5)
print(scores.mean())

#1. split the dataset: train and test and then fit the classifier using X_train and Y_train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)
rmodel.fit(X_train,Y_train)

#2. test the classifier using 3 samples
my_tests = [[0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3],[0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3],[1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4]]
Y_prediction_test= rmodel.predict(my_tests)
print(Y_prediction_test)

#3. print the predictions
Y_prediction = rmodel.predict(X_test)
print("Y_prediction:",Y_prediction)
print("Y_test:",Y_test)

#4. check/test 5 metrics for classification
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_test, Y_prediction)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_test, Y_prediction))
print("Precision score:",metrics.precision_score(Y_test, Y_prediction))
print("Recall score:",metrics.recall_score(Y_test, Y_prediction))
print("F1 score:",f1_score(Y_test, Y_prediction))

0.8176161616161617
[0 0 1]
Y_prediction: [1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 0 0 0
 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0]
Y_test: 90     1
254    0
283    0
444    0
474    0
      ..
381    0
56     0
439    0
60     0
208    0
Name: NObeyesdad, Length: 100, dtype: int64
Confusion Matrix:
[[57  3]
 [ 6 34]]
Accuracy score: 0.91
Precision score: 0.918918918918919
Recall score: 0.85
F1 score: 0.8831168831168831

/home/izabella/anaconda3/envs/my_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [86]:
#BOOSTING: ADABOOST
seed = 7
num_trees = 30
kfold = model_selection.KFold(n_splits=10, shuffle=True, random_state=seed)

model = AdaBoostClassifier(base_estimator = nusvc, n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)

print(results)
print(results.mean())

#split the dataset: train + test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)
model.fit(X_train,Y_train)

#Predict the response for test dataset
Y_prediction = model.predict(X_test)
print("Y_prediction:",Y_prediction)
print("Y_test:",Y_test)

#test the model using 3 samples
my_tests = [[0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3],[0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3],[1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4]]
Y_prediction_test= model.predict(my_tests)
print("Prediction form my given test:",Y_prediction_test)

#check/test 5 metrics for classification
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_test, Y_prediction)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_test, Y_prediction))
print("Precision score:",metrics.precision_score(Y_test, Y_prediction))
print("Recall score:",metrics.recall_score(Y_test, Y_prediction))
print("F1 score:",f1_score(Y_test, Y_prediction))

[0.92       0.98       0.96       0.92       0.96       0.92
 0.96       0.98       0.94       0.97959184]
0.9519591836734692
Y_prediction: [1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 1 0 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0
 0 1 0 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0]
Y_test: 90     1
254    0
283    0
444    0
474    0
      ..
381    0
56     0
439    0
60     0
208    0
Name: NObeyesdad, Length: 100, dtype: int64
Prediction form my given test: [0 0 1]
Confusion Matrix:
[[58  2]
 [ 2 38]]
Accuracy score: 0.96
Precision score: 0.95
Recall score: 0.95
F1 score: 0.9500000000000001

/home/izabella/anaconda3/envs/my_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

In [88]:
#GRADIENT BOOSTING
num_trees = 50
kfold = model_selection.KFold(n_splits=10)

model = GradientBoostingClassifier(n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

X_for_train, X_for_test, Y_for_train, Y_for_test = train_test_split(X, Y, test_size = 0.15, random_state = 0)

my_test = [[0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3],[0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3],[1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4]]

# Train GradientBoostingClassifier: fitting the X and Y
gboost = GradientBoostingClassifier(n_estimators=100,learning_rate=1)
gboost.fit(X_for_train, Y_for_train)

#Predict the response for test dataset
Y_prediction = gboost.predict(X_test)
# test using the sample given: test the model using 3 new samples, and print the results
Y_prediction_test= gboost.predict(my_test)

#print the predictions
print("Prediction form my given test:",Y_prediction_test)
print("Prediction:",Y_prediction)

#check/test 5 metrics for classification
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_test, Y_prediction)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_test, Y_prediction))
print("Precision score:",metrics.precision_score(Y_test, Y_prediction))
print("Recall score:",metrics.recall_score(Y_test, Y_prediction))
print("F1 score:",f1_score(Y_test, Y_prediction))

0.9618775510204081
Prediction form my given test: [0 0 1]
Prediction: [1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0
 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0]
Confusion Matrix:
[[60  0]
 [ 3 37]]
Accuracy score: 0.97
Precision score: 1.0
Recall score: 0.925
F1 score: 0.961038961038961

/home/izabella/anaconda3/envs/my_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(